bot:
  # Discord botunuzun tokeni
  token: '203ff7f93f41baff4af47a600885556f42b73e819eceb21b1e80e925c7ff158f'
  # Discord botunuzun application idsi
  id: '1311197899383767070 '
  # Discord botunun durum kÄ±smÄ±
  status:
    # Discord botunun aÃ§Ä±klma kÄ±smÄ±ndaki event; playing = Oynuyor, streaming = YayÄ±nda, listening = Dinliyor, watching = Ä°zliyor, competing = YarÄ±ÅŸmada yarÄ±ÅŸÄ±yor.
    activity: 'streaming'
    # Discord botunun aÃ§Ä±klama yazÄ±sÄ±; %onDutyPolice% yazarak aktif mesaideki memurlarÄ±n sayÄ±sÄ±nÄ± gÃ¶sterebilirsiniz.
    text: '%onDutyPolice% kiÅŸi ÅŸuanda mesaide!'
    # Discord botunun aÃ§Ä±klma kÄ±smÄ±ndaki event streaming olarak ayarlanÄ±rsa aÅŸaÄŸÄ±daki twitch kÄ±smÄ±nÄ± doldurunuz.
    twitch: 'https://www.twitch.tv/example'
    # Discord botunun aktiflik kÄ±smÄ±; online = Aktif, idle = BoÅŸta, dnd = RahatsÄ±z Etmeyin, invisible = Ã‡evrimdÄ±ÅŸÄ±.
    status: 'idle'
guild:
  # Discord sunucunuzun idsi
  id: ''
settings:
  departmentName: 'MRPD'
  departmentLogo: 'https://forum-cfx-re.akamaized.net/optimized/5X/1/9/1/4/191405706bc8323670bf6d1151202a569de55823_2_1024x576.jpeg'
  departmentBanner: 'https://forum-cfx-re.akamaized.net/optimized/5X/1/9/1/4/191405706bc8323670bf6d1151202a569de55823_2_1024x576.jpeg'
  departmentColor: '#0000ff'
  roles:
    # RÃ¼tbe rollerinin idleri
    officers: ['', '']
  channels:
    # Log kanalÄ±nÄ±n idsi
    log: ''
  # Mesaj iÃ§erikelrinde kulanÄ±lan emojiler, ğŸ“‹ ÅŸeklinde, :emojiAdÄ±: ÅŸeklinde veya idsiyle kullanÄ±labilir.
  emojis:
    department: 'ğŸ‘®'
    on: 'ğŸŸ©'
    off: 'ğŸŸ¥'
    warning: 'âš ï¸'
    info: 'ğŸ“‹'
    clock: 'â²ï¸'
commands:
    # Aktif mesaideki Ã¼yeleri gÃ¶steren komut
    activeDuty:
      # Bu komutu kullanabilmek iÃ§in gereken rol
      requiredRole: ''
